name: deploy-function

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install zip
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Package Azure Function
        working-directory: src/functions/incident
        run: zip -r ../../../functionapp.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: functionapp-package
          path: functionapp.zip
